INSERT INTO signup_city VALUES ('New York', 'NY');
INSERT INTO signup_city VALUES ('Los Angeles', 'CA');
INSERT INTO signup_city VALUES ('Chicago', 'IL');
INSERT INTO signup_city VALUES ('Houston', 'TX');
INSERT INTO signup_city VALUES ('Philadelphia', 'PA');
INSERT INTO signup_city VALUES ('Phoenix', 'AZ');
INSERT INTO signup_city VALUES ('San Antonio', 'TX');
INSERT INTO signup_city VALUES ('San Diego', 'CA');
INSERT INTO signup_city VALUES ('Dallas', 'TX');
INSERT INTO signup_city VALUES ('San Jose', 'CA');
INSERT INTO signup_city VALUES ('Austin', 'TX');
INSERT INTO signup_city VALUES ('Jacksonville', 'FL');
INSERT INTO signup_city VALUES ('San Francisco', 'CA');
INSERT INTO signup_city VALUES ('Indianapolis', 'IN');
INSERT INTO signup_city VALUES ('Columbus', 'OH');
INSERT INTO signup_city VALUES ('Fort Worth', 'TX');
INSERT INTO signup_city VALUES ('Charlotte', 'NC');
INSERT INTO signup_city VALUES ('Detroit', 'MI');
INSERT INTO signup_city VALUES ('El Paso', 'TX');
INSERT INTO signup_city VALUES ('Seattle', 'WA');
INSERT INTO signup_city VALUES ('Denver', 'CO');
INSERT INTO signup_city VALUES ('Washington', 'DC');
INSERT INTO signup_city VALUES ('Memphis', 'TN');
INSERT INTO signup_city VALUES ('Boston', 'MA');
INSERT INTO signup_city VALUES ('Nashville-Davidson', 'TN');
INSERT INTO signup_city VALUES ('Baltimore', 'MD');
INSERT INTO signup_city VALUES ('Oklahoma City', 'OK');
INSERT INTO signup_city VALUES ('Portland', 'OR');
INSERT INTO signup_city VALUES ('Las Vegas', 'NV');
INSERT INTO signup_city VALUES ('Louisville/Jefferson County', 'KY');
INSERT INTO signup_city VALUES ('Milwaukee', 'WI');
INSERT INTO signup_city VALUES ('Albuquerque', 'NM');
INSERT INTO signup_city VALUES ('Tucson', 'AZ');
INSERT INTO signup_city VALUES ('Fresno', 'CA');
INSERT INTO signup_city VALUES ('Sacramento', 'CA');
INSERT INTO signup_city VALUES ('Long Beach', 'CA');
INSERT INTO signup_city VALUES ('Kansas City', 'MO');
INSERT INTO signup_city VALUES ('Mesa', 'AZ');
INSERT INTO signup_city VALUES ('Atlanta', 'GA');
INSERT INTO signup_city VALUES ('Virginia Beach', 'VA');
INSERT INTO signup_city VALUES ('Omaha', 'NE');
INSERT INTO signup_city VALUES ('Colorado Springs', 'CO');
INSERT INTO signup_city VALUES ('Raleigh', 'NC');
INSERT INTO signup_city VALUES ('Miami', 'FL');
INSERT INTO signup_city VALUES ('Oakland', 'CA');
INSERT INTO signup_city VALUES ('Minneapolis', 'MN');
INSERT INTO signup_city VALUES ('Tulsa', 'OK');
INSERT INTO signup_city VALUES ('Cleveland', 'OH');
INSERT INTO signup_city VALUES ('Wichita', 'KS');
INSERT INTO signup_city VALUES ('New Orleans', 'LA');
INSERT INTO signup_city VALUES ('Arlington', 'TX');
INSERT INTO signup_city VALUES ('Bakersfield', 'CA');
INSERT INTO signup_city VALUES ('Tampa', 'FL');
INSERT INTO signup_city VALUES ('Aurora', 'CO');
INSERT INTO signup_city VALUES ('Honolul', 'HI');
INSERT INTO signup_city VALUES ('Anaheim', 'CA');
INSERT INTO signup_city VALUES ('Santa Ana', 'CA');
INSERT INTO signup_city VALUES ('Corpus Christi', 'TX');
INSERT INTO signup_city VALUES ('Riverside', 'CA');
INSERT INTO signup_city VALUES ('St. Louis', 'MO');
INSERT INTO signup_city VALUES ('Lexington-Fayette', 'KY');
INSERT INTO signup_city VALUES ('Pittsburgh', 'PA');
INSERT INTO signup_city VALUES ('Stockton', 'CA');
INSERT INTO signup_city VALUES ('Anchorage', 'AK');
INSERT INTO signup_city VALUES ('Cincinnati', 'OH');
INSERT INTO signup_city VALUES ('St. Paul', 'MN');
INSERT INTO signup_city VALUES ('Greensboro', 'NC');
INSERT INTO signup_city VALUES ('Toledo', 'OH');
INSERT INTO signup_city VALUES ('Newark', 'NJ');
INSERT INTO signup_city VALUES ('Plano', 'TX');
INSERT INTO signup_city VALUES ('Henderson', 'NV');
INSERT INTO signup_city VALUES ('Lincoln', 'NE');
INSERT INTO signup_city VALUES ('Orlando', 'FL');
INSERT INTO signup_city VALUES ('Jersey City', 'NJ');
INSERT INTO signup_city VALUES ('Chula Vista', 'CA');
INSERT INTO signup_city VALUES ('Buffalo', 'NY');
INSERT INTO signup_city VALUES ('Fort Wayne', 'IN');
INSERT INTO signup_city VALUES ('Chandler', 'AZ');
INSERT INTO signup_city VALUES ('St. Petersburg', 'FL');
INSERT INTO signup_city VALUES ('Laredo', 'TX');
INSERT INTO signup_city VALUES ('Durham', 'NC');
INSERT INTO signup_city VALUES ('Irvine', 'CA');
INSERT INTO signup_city VALUES ('Madison', 'WI');
INSERT INTO signup_city VALUES ('Norfolk', 'VA');
INSERT INTO signup_city VALUES ('Lubbock', 'TX');
INSERT INTO signup_city VALUES ('Gilbert', 'AZ');
INSERT INTO signup_city VALUES ('Winston-Salem', 'NC');
INSERT INTO signup_city VALUES ('Glendale', 'AZ');
INSERT INTO signup_city VALUES ('Reno', 'NV');
INSERT INTO signup_city VALUES ('Hialeah', 'FL');
INSERT INTO signup_city VALUES ('Garland', 'TX');
INSERT INTO signup_city VALUES ('Chesapeake', 'VA');
INSERT INTO signup_city VALUES ('Irving', 'TX');
INSERT INTO signup_city VALUES ('North Las Vegas', 'NV');
INSERT INTO signup_city VALUES ('Scottsdale', 'AZ');
INSERT INTO signup_city VALUES ('Baton Rouge', 'LA');
INSERT INTO signup_city VALUES ('Fremont', 'CA');
INSERT INTO signup_city VALUES ('Richmond', 'VA');
INSERT INTO signup_city VALUES ('Boise City', 'ID');
INSERT INTO signup_city VALUES ('San Bernardino', 'CA');